apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: numberreg
  namespace: default
  labels:
    app: numberreg
spec:
  template:
    metadata:
      labels:
        app: numberreg
      annotations:
        autoscaling.knative.dev/target: "25"
        autoscaling.knative.dev/initial-scale: "2"
        autoscaling.knative.dev/min-scale: "2"
    spec:
      containers:
      - name: numberreg
        image: ddocker122/number_recognization_service:v1
        resources:
          requests:
            #memory: "3000Mi"
            #cpu: "500m"
          limits:
            #memory: "3000Mi"
            cpu: "2000m"
        ports:
        - containerPort: 5000
        readinessProbe:
          periodSeconds: 1
          timeoutSeconds: 1
