---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - drlscaling.knativescaling.dcn.ssu.ac.kr
  resources:
  - drlscaleactions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - drlscaling.knativescaling.dcn.ssu.ac.kr
  resources:
  - drlscaleactions/finalizers
  verbs:
  - update
- apiGroups:
  - drlscaling.knativescaling.dcn.ssu.ac.kr
  resources:
  - drlscaleactions/status
  verbs:
  - get
  - patch
  - update
